package com.telecomjs.mappers;

import com.telecomjs.entities.Cust;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.cache.annotation.Cacheable;

@Mapper
public interface CustMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long custId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust
     *
     * @mbggenerated
     */
    int insert(Cust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust
     *
     * @mbggenerated
     */
    int insertSelective(Cust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust
     *
     * @mbggenerated
     */
    Cust selectByPrimaryKey(Long custId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Cust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Cust record);

    //@Select("select * from cust where cust_id = #{custId} ")
    @Cacheable(value = "cust",key = "'Cust#'+#root.methodName+'#'+#p0" )
    public Cust selectCust(@Param("custId") long custId);
}