package com.telecomjs.entities;

import java.io.Serializable;
import java.util.Date;

public class Cust implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust.CUST_ID
     *
     * @mbggenerated
     */
    private Long custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust.CUST_NAME
     *
     * @mbggenerated
     */
    private String custName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust.CUST_CERT
     *
     * @mbggenerated
     */
    private String custCert;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust.STATUS_DATE
     *
     * @mbggenerated
     */
    private Date statusDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust.CUST_ID
     *
     * @return the value of cust.CUST_ID
     *
     * @mbggenerated
     */
    public Long getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust.CUST_ID
     *
     * @param custId the value for cust.CUST_ID
     *
     * @mbggenerated
     */
    public void setCustId(Long custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust.CUST_NAME
     *
     * @return the value of cust.CUST_NAME
     *
     * @mbggenerated
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust.CUST_NAME
     *
     * @param custName the value for cust.CUST_NAME
     *
     * @mbggenerated
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust.CUST_CERT
     *
     * @return the value of cust.CUST_CERT
     *
     * @mbggenerated
     */
    public String getCustCert() {
        return custCert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust.CUST_CERT
     *
     * @param custCert the value for cust.CUST_CERT
     *
     * @mbggenerated
     */
    public void setCustCert(String custCert) {
        this.custCert = custCert == null ? null : custCert.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust.CREATE_DATE
     *
     * @return the value of cust.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust.CREATE_DATE
     *
     * @param createDate the value for cust.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust.STATUS_DATE
     *
     * @return the value of cust.STATUS_DATE
     *
     * @mbggenerated
     */
    public Date getStatusDate() {
        return statusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust.STATUS_DATE
     *
     * @param statusDate the value for cust.STATUS_DATE
     *
     * @mbggenerated
     */
    public void setStatusDate(Date statusDate) {
        this.statusDate = statusDate;
    }


}